apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: web-svc
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  externalIPs:
  - 159.89.127.14
  - 159.89.112.76
  - 165.227.39.81
  selector:
    app: web
